version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123okAdmin
      POSTGRES_DB: golang
    container_name: golangdb
    volumes:
      - ./postgres:/var/lib/postgresql/data  